name: wimmobeta
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  url_launcher: ^5.7.1
  http: any
  carousel_pro: ^1.0.0
  searchable_dropdown: ^1.1.3
  cached_network_image: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg
    - assets/logo.png
    - assets/logo2.png
    - assets/image1.jpg
    - assets/chambre.png
    - assets/cuisine.png
    - assets/salon.png
    - assets/bain.png
    - assets/admi.png
    - assets/dim.png
  fonts:
    - family: SF Pro Display
      fonts:
      - asset: fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
      - asset: fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: fonts/SF-Pro-Display-Black.otf
        weight: 900